# Generated by Django 3.2.6 on 2021-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210817_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر ها'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_supporter',
            field=models.BooleanField(default=False, verbose_name='پشتیبانی'),
        ),
    ]
