# Generated by Django 3.2.5 on 2021-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع')),
                ('sup_type', models.CharField(choices=[('d', 'پشتیبانی'), ('p', 'حسابداری')], max_length=50, verbose_name='دپارتمان')),
                ('content', models.TextField(blank=True, null=True, verbose_name='پیام')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_sup', models.BooleanField(default=True, verbose_name='دپارتمان پشتیبانی')),
                ('is_accountants', models.BooleanField(default=True, verbose_name='دپارتمان حسابداری')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
