# Generated by Django 3.2.6 on 2021-08-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210817_1458'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sup_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department', verbose_name='دپارتمان'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
