# Generated by Django 3.2.5 on 2021-07-30 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210726_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pb_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاریخ انتشار'),
        ),
    ]
