# Generated by Django 3.2.5 on 2021-07-30 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_pb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pb_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ انتشار'),
        ),
    ]
