# Generated by Django 3.2.5 on 2021-07-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_pb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sup_type',
            field=models.CharField(choices=[('s', 'پشتیبانی'), ('a', 'حسابداری')], max_length=50, verbose_name='دپارتمان'),
        ),
    ]
