# Generated by Django 3.2.5 on 2021-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_sup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default=None, upload_to='media/ticket', verbose_name='عکس'),
        ),
    ]
