# Generated by Django 3.2.5 on 2021-07-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='User',
            new_name='user',
        ),
    ]
