# Generated by Django 3.2.5 on 2021-07-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_rename_user_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_ticket_ticket_response_+', to='ticket.Response', verbose_name='پاسخ ها'),
        ),
        migrations.AlterField(
            model_name='response',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ticket.ticket', verbose_name='تیکت'),
        ),
    ]
