# Generated by Django 3.2.5 on 2021-07-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20210731_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='response',
        ),
        migrations.AlterField(
            model_name='response',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket', verbose_name='تیکت'),
        ),
    ]
