# Generated by Django 3.2.5 on 2021-07-31 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20210731_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='pb_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ انتشار'),
        ),
    ]
