# Generated by Django 3.2.5 on 2021-07-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_response_pb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/ticket', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
