# Generated by Django 3.2.5 on 2021-08-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20210731_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-pb_date'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-pb_date'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
