# Generated by Django 3.2.5 on 2021-08-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20210804_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-pb_date'], 'verbose_name': 'جواب', 'verbose_name_plural': 'جواب ها'},
        ),
    ]
