# Generated by Django 3.2.5 on 2021-08-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_alter_response_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
